import {
  AssessmentStatus,
  Prisma,
  prisma
} from "@evolve-edge/db";
import {
  RevenuePlanCode,
  getRevenuePlanDefinition
} from "./revenue-catalog";

type UsageDbClient = Prisma.TransactionClient | typeof prisma;

export const USAGE_METRIC_KEYS = [
  "reportsGenerated",
  "activeAssessments",
  "monitoredAssets",
  "seats",
  "apiCalls",
  "storageBytes",
  "aiProcessingRuns"
] as const;

export type UsageMetricKey = (typeof USAGE_METRIC_KEYS)[number];
export type UsageEnforcement = "hard" | "soft" | "visibility";
export type UsageStatus = "ok" | "warning" | "exceeded" | "unlimited";

export type UsageMetricSnapshot = {
  key: UsageMetricKey;
  label: string;
  description: string;
  unit: "count" | "bytes";
  used: number;
  limit: number | null;
  remaining: number | null;
  percentUsed: number | null;
  enforcement: UsageEnforcement;
  warningThresholdPercent: number;
  status: UsageStatus;
  isConfigured: boolean;
  shortLabel: string;
  usageLabel: string;
  helperText: string;
  upgradeTitle: string;
  upgradeBody: string;
  actionHref: string;
  actionLabel: string;
};

export type OrganizationUsageMeteringSnapshot = {
  organizationId: string;
  planCode: string | null;
  metrics: UsageMetricSnapshot[];
  topWarning: UsageMetricSnapshot | null;
};

type MetricConfig = {
  label: string;
  shortLabel: string;
  description: string;
  unit: "count" | "bytes";
  enforcement: UsageEnforcement;
  warningThresholdPercent: number;
  actionHref: string;
  actionLabel: string;
  planLimitKey: UsageMetricKey;
};

const METRIC_CONFIG: Record<UsageMetricKey, MetricConfig> = {
  reportsGenerated: {
    label: "Reports generated",
    shortLabel: "Reports",
    description: "Executive and stakeholder-facing reports created in this workspace.",
    unit: "count",
    enforcement: "soft",
    warningThresholdPercent: 80,
    actionHref: "/pricing",
    actionLabel: "Compare plans",
    planLimitKey: "reportsGenerated"
  },
  activeAssessments: {
    label: "Active assessments",
    shortLabel: "Assessments",
    description: "Non-archived assessments currently taking up live workspace capacity.",
    unit: "count",
    enforcement: "hard",
    warningThresholdPercent: 80,
    actionHref: "/pricing",
    actionLabel: "Upgrade assessment capacity",
    planLimitKey: "activeAssessments"
  },
  monitoredAssets: {
    label: "Monitored assets",
    shortLabel: "Assets",
    description: "Registered vendors and AI models tracked as live operational assets.",
    unit: "count",
    enforcement: "soft",
    warningThresholdPercent: 80,
    actionHref: "/pricing",
    actionLabel: "Upgrade monitored asset capacity",
    planLimitKey: "monitoredAssets"
  },
  seats: {
    label: "Workspace seats",
    shortLabel: "Seats",
    description: "Active members assigned to the organization workspace.",
    unit: "count",
    enforcement: "hard",
    warningThresholdPercent: 75,
    actionHref: "/dashboard/settings",
    actionLabel: "Open billing settings",
    planLimitKey: "seats"
  },
  apiCalls: {
    label: "API calls",
    shortLabel: "API",
    description: "Tracked API requests against product-integrated access surfaces.",
    unit: "count",
    enforcement: "visibility",
    warningThresholdPercent: 80,
    actionHref: "/pricing",
    actionLabel: "Review API capacity",
    planLimitKey: "apiCalls"
  },
  storageBytes: {
    label: "Storage",
    shortLabel: "Storage",
    description: "Stored evidence and uploaded file volume measured in bytes when file sizes are available.",
    unit: "bytes",
    enforcement: "visibility",
    warningThresholdPercent: 80,
    actionHref: "/pricing",
    actionLabel: "Review storage capacity",
    planLimitKey: "storageBytes"
  },
  aiProcessingRuns: {
    label: "AI processing runs",
    shortLabel: "AI runs",
    description: "Queued or completed AI analysis jobs generated by assessment workflows.",
    unit: "count",
    enforcement: "soft",
    warningThresholdPercent: 80,
    actionHref: "/pricing",
    actionLabel: "Upgrade AI processing capacity",
    planLimitKey: "aiProcessingRuns"
  }
};

function formatCount(value: number) {
  return new Intl.NumberFormat("en-US").format(value);
}

export function formatBytes(value: number) {
  if (value < 1_000) {
    return `${value} B`;
  }

  if (value < 1_000_000) {
    return `${(value / 1_000).toFixed(1)} KB`;
  }

  if (value < 1_000_000_000) {
    return `${(value / 1_000_000).toFixed(1)} MB`;
  }

  return `${(value / 1_000_000_000).toFixed(1)} GB`;
}

function formatMetricValue(unit: "count" | "bytes", value: number) {
  return unit === "bytes" ? formatBytes(value) : formatCount(value);
}

export function getPlanUsageLimits(planCode: string | null | undefined) {
  const plan = getRevenuePlanDefinition(planCode as RevenuePlanCode | null | undefined);
  return plan?.usageLimits ?? null;
}

function buildMetricSnapshot(input: {
  key: UsageMetricKey;
  used: number;
  planCode: string | null;
}) {
  const config = METRIC_CONFIG[input.key];
  const planLimits = getPlanUsageLimits(input.planCode);
  const limit = planLimits?.[config.planLimitKey] ?? null;
  const remaining = limit === null ? null : Math.max(limit - input.used, 0);
  const percentUsed =
    limit && limit > 0 ? Math.min(999, Math.round((input.used / limit) * 100)) : null;
  const status: UsageStatus =
    limit === null
      ? "unlimited"
      : input.used >= limit
        ? "exceeded"
        : percentUsed !== null && percentUsed >= config.warningThresholdPercent
          ? "warning"
          : "ok";
  const usageLabel =
    limit === null
      ? `${formatMetricValue(config.unit, input.used)} used`
      : `${formatMetricValue(config.unit, input.used)} of ${formatMetricValue(config.unit, limit)}`;
  const helperText =
    limit === null
      ? "Tracked for operational visibility. This metric is not capped on the current plan."
      : status === "exceeded"
        ? config.enforcement === "hard"
          ? "Current plan capacity is exhausted. Upgrade or reduce usage before adding more."
          : "You have moved past the recommended usage range for this plan."
        : status === "warning"
          ? remaining !== null
            ? `${formatMetricValue(config.unit, remaining)} remaining before the current plan limit.`
            : "Approaching the recommended threshold for this metric."
          : remaining !== null
            ? `${formatMetricValue(config.unit, remaining)} remaining on the current plan.`
            : "Usage is within the current plan allowance.";
  const upgradeTitle =
    status === "exceeded"
      ? `${config.label} limit reached`
      : `${config.label} nearing plan capacity`;
  const upgradeBody =
    status === "exceeded"
      ? `The workspace has reached the ${config.label.toLowerCase()} allowance on the current plan.`
      : `The workspace is using most of its ${config.label.toLowerCase()} allowance on the current plan.`;

  return {
    key: input.key,
    label: config.label,
    description: config.description,
    unit: config.unit,
    used: input.used,
    limit,
    remaining,
    percentUsed,
    enforcement: config.enforcement,
    warningThresholdPercent: config.warningThresholdPercent,
    status,
    isConfigured: limit !== null,
    shortLabel: config.shortLabel,
    usageLabel,
    helperText,
    upgradeTitle,
    upgradeBody,
    actionHref: config.actionHref,
    actionLabel: config.actionLabel
  } satisfies UsageMetricSnapshot;
}

export async function getOrganizationUsageMeteringSnapshot(
  organizationId: string,
  planCode: string | null,
  db: UsageDbClient = prisma
): Promise<OrganizationUsageMeteringSnapshot> {
  const [
    reportsGenerated,
    activeAssessments,
    seats,
    vendorCount,
    modelCount,
    analysisRuns,
    storageAggregate
  ] = await Promise.all([
    db.report.count({
      where: { organizationId }
    }),
    db.assessment.count({
      where: {
        organizationId,
        status: {
          not: AssessmentStatus.ARCHIVED
        }
      }
    }),
    db.organizationMember.count({
      where: { organizationId }
    }),
    db.vendor.count({
      where: { organizationId }
    }),
    db.aIModel.count({
      where: { organizationId }
    }),
    db.analysisJob.count({
      where: {
        assessment: {
          organizationId
        }
      }
    }),
    db.evidenceFile.aggregate({
      where: {
        organizationId
      },
      _sum: {
        sizeBytes: true
      }
    })
  ]);

  const metrics = [
    buildMetricSnapshot({
      key: "reportsGenerated",
      used: reportsGenerated,
      planCode
    }),
    buildMetricSnapshot({
      key: "activeAssessments",
      used: activeAssessments,
      planCode
    }),
    buildMetricSnapshot({
      key: "monitoredAssets",
      used: vendorCount + modelCount,
      planCode
    }),
    buildMetricSnapshot({
      key: "seats",
      used: seats,
      planCode
    }),
    buildMetricSnapshot({
      key: "apiCalls",
      used: 0,
      planCode
    }),
    buildMetricSnapshot({
      key: "storageBytes",
      used: storageAggregate._sum.sizeBytes ?? 0,
      planCode
    }),
    buildMetricSnapshot({
      key: "aiProcessingRuns",
      used: analysisRuns,
      planCode
    })
  ];

  const topWarning =
    metrics
      .filter((metric) => metric.status === "exceeded" || metric.status === "warning")
      .sort((left, right) => {
        const leftWeight = left.status === "exceeded" ? 2 : 1;
        const rightWeight = right.status === "exceeded" ? 2 : 1;

        if (leftWeight !== rightWeight) {
          return rightWeight - leftWeight;
        }

        return (right.percentUsed ?? 0) - (left.percentUsed ?? 0);
      })[0] ?? null;

  return {
    organizationId,
    planCode,
    metrics,
    topWarning
  };
}

export function getUsageMetricSnapshot(
  snapshot: OrganizationUsageMeteringSnapshot,
  key: UsageMetricKey
) {
  return snapshot.metrics.find((metric) => metric.key === key) ?? null;
}

export function getUsageThresholdEventMetricKey(metric: UsageMetricKey) {
  switch (metric) {
    case "reportsGenerated":
      return "reports_generated";
    case "activeAssessments":
      return "active_assessments";
    case "monitoredAssets":
      return "monitored_assets";
    case "seats":
      return "seats";
    case "apiCalls":
      return "api_calls";
    case "storageBytes":
      return "storage_bytes";
    case "aiProcessingRuns":
      return "ai_processing_runs";
  }
}
